---
filepath: X:\KI Praktikum\validate_Data\2023_08_23_filtered_data\Versuch28_08_2023_trocken_iso_5s.csv
ipofilepath: X:\KI Praktikum\validate_Data\2023_08_23_filtered_data\test_config_Versuch28_08_2023_trocken_iso_5s.csv
---
filepath: X:\KI Praktikum\validate_Data\2023_08_23_filtered_data\Versuch29_08_2023_trocken_iso_5s.csv
ipofilepath: X:\KI Praktikum\validate_Data\2023_08_23_filtered_data\test_config_Versuch29_08_2023_trocken_iso_5s.csv